package com.proyecto1.gui;
import com.proyecto1.MainFrame;
import javax.swing.JOptionPane;
import com.proyecto1.models.Product;
import com.proyecto1.models.Wearhouse;
import com.proyecto1.gui.MainPanel;
import javax.swing.JFrame;

// @author andresbucarello

public class AgregarProducto extends javax.swing.JPanel {
    
    int cantidad = 5;
    Wearhouse[] almacenes = new Wearhouse[cantidad];
    String nombre;
    int stock;
    int opciones;
    Wearhouse almacenSeleccionado;
    
    /**
     * Creates new form AgregarProducto
     */
    public AgregarProducto() {
        initComponents();
        // crear array de los almacenes existentes
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        listaAlmacenes = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        titulo3 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        titulo4 = new javax.swing.JLabel();
        fieldCantidad = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        botonGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(630, 450));
        setMinimumSize(new java.awt.Dimension(630, 450));
        setPreferredSize(new java.awt.Dimension(630, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo1.setFont(new java.awt.Font("Silom", 0, 48)); // NOI18N
        titulo1.setText("AGREGAR PRODUCTO");
        add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        titulo2.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo2.setText("SELECCIONE EL ALMACEN :");
        add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, -1));

        listaAlmacenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAlmacenesActionPerformed(evt);
            }
        });
        add(listaAlmacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 580, 20));

        titulo3.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo3.setText("INGRESE EL NOMBRE DEL PRODUCTO :");
        add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 260, 20));

        fieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNombreFocusLost(evt);
            }
        });
        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });
        add(fieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 320, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 580, 20));

        titulo4.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo4.setText("INGRESE LA CANTIDAD DEL PRODUCTO :");
        add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 280, 20));

        fieldCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCantidadFocusLost(evt);
            }
        });
        fieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCantidadActionPerformed(evt);
            }
        });
        add(fieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 300, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 580, 20));

        botonGuardar.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.setEnabled(false);
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 120, -1));

        jButton1.setText("<----");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    private boolean encontrar(){
        for (Wearhouse almacen : almacenes) {
            if(almacenSeleccionado.name.equals(almacen.name)){
                for (Product producto : almacen.products){
                    if(nombre.equals(producto.name)){
                        return true;
                    }
                }
            }    
        }
        return false;
    }
    
    private int validarInt(String num){
        try{
            stock=Integer.parseInt(num);
            if(stock<=0){
                JOptionPane.showMessageDialog(null, " ERROR LA CANTIDAD INGRSADA NO ES VALIDA ");
                fieldCantidad.setText("");
                return 0;
            }
            return stock;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " ERROR LA CANTIDAD INGRSADA NO ES VALIDA ");
            fieldCantidad.setText("");
            return 0;
        }
    }
    
    private String validarStr(String nombre){
        try{
            String nombreProducto=fieldNombre.getText();
            boolean encontrado=encontrar();
            if(encontrado || !nombre.isEmpty()){
                if(encontrado){
                    JOptionPane.showMessageDialog(null, " EL PRODUCTO YA EXISTE, EL NOMBRE NO ES VALIDO: ");
                }else{
                    JOptionPane.showMessageDialog(null, " ERROR EL NOMBRE INGRESADO NO ES VALIDO: ");
                }
                fieldNombre.setText("");
                return "";
            }
            return nombreProducto;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " ERROR EL NOMBRE INGRESADO NO ES VALIDO: ");
            fieldNombre.setText("");
            return "";
        }
    }
    
    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        String nombreProducto=fieldNombre.getText();
        nombre=validarStr(nombreProducto);
        if(stock>0 && !nombre.isEmpty()){
            botonGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void fieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCantidadActionPerformed
        String num =fieldCantidad.getText();
        stock = validarInt(num);
        if(stock>0 && !nombre.isEmpty()){
            botonGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_fieldCantidadActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        Product producto=new Product(nombre, stock);
        for (Wearhouse almacen : almacenes) {
            if(almacenSeleccionado.name.equals(almacen.name)){
                almacen.products.pushBack(producto);
                break;
            }
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void listaAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAlmacenesActionPerformed
        // La lista debe mostrar los almacenes
        almacenSeleccionado=(Wearhouse) listaAlmacenes.getSelectedItem();
    }//GEN-LAST:event_listaAlmacenesActionPerformed

    private void fieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNombreFocusLost
        String nombreProducto=fieldNombre.getText();
        nombre=validarStr(nombreProducto);
        if(stock>0 && !nombre.isEmpty()){
            botonGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_fieldNombreFocusLost

    private void fieldCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCantidadFocusLost
        String num =fieldCantidad.getText();
        stock = validarInt(num);
        if(stock>0 && !nombre.isEmpty()){
            botonGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_fieldCantidadFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField fieldCantidad;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> listaAlmacenes;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    // End of variables declaration//GEN-END:variables
}
