package com.proyecto1.gui;
import com.proyecto1.containers.Graph;
import com.proyecto1.containers.Vector;
import javax.swing.JOptionPane;
import com.proyecto1.models.Product;
import com.proyecto1.models.Warehouse;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

// @author andresbucarello

public class AgregarProducto extends MenuComponent {
    
    Vector<Warehouse> almacenes;
    Warehouse almacenSeleccionadoW;
    String nombre;
    int stock;
    DefaultComboBoxModel<String> disponibles = new DefaultComboBoxModel();
    
    /**
     * Creates new form AgregarProducto
     */
    public AgregarProducto(MainPanel mainMenuPanel) {
        super(mainMenuPanel);
        initComponents();
        
        almacenes= Graph.getInstance().warehouses;
        cargarCombo(listaAlmacenes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        listaAlmacenes = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        titulo3 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        titulo4 = new javax.swing.JLabel();
        fieldCantidad = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        botonGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(960, 720));
        setMinimumSize(new java.awt.Dimension(960, 720));
        setPreferredSize(new java.awt.Dimension(960, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo1.setFont(new java.awt.Font("Silom", 0, 65)); // NOI18N
        titulo1.setText("AGREGAR PRODUCTO");
        add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        titulo2.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        titulo2.setText("SELECCIONE EL ALMACEN :");
        add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 380, -1));

        listaAlmacenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAlmacenesActionPerformed(evt);
            }
        });
        add(listaAlmacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 320, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 880, 20));

        titulo3.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        titulo3.setText("INGRESE EL NOMBRE DEL PRODUCTO :");
        add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 450, 20));

        fieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNombreFocusLost(evt);
            }
        });
        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });
        add(fieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 420, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 880, 20));

        titulo4.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        titulo4.setText("INGRESE LA CANTIDAD DEL PRODUCTO :");
        add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 470, 20));

        fieldCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCantidadFocusLost(evt);
            }
        });
        fieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCantidadActionPerformed(evt);
            }
        });
        add(fieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 400, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 880, 20));

        botonGuardar.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.setEnabled(false);
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, 180, -1));

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    private boolean encontrarProducto(String nombreProducto){
        for (Warehouse almacen : almacenes) {
            if(almacenSeleccionadoW.name.equals(almacen.name)){
                for (Product producto : almacen.products){
                    if(nombreProducto.equalsIgnoreCase(producto.name)){
                        return true;
                    }
                }
            }    
        }
        return false;
    }
    
    private void cargarCombo(JComboBox c) {
        c.setModel(disponibles);
        for (Warehouse almacen: almacenes) {
            disponibles.addElement(almacen.name);
        }
    }
    
    private Warehouse buscarWearhouse(Vector<Warehouse> almacenes, String nombre){
        for (Warehouse almacen : almacenes) {
            if(nombre.equals(almacen.name)){
                return almacen;    
            }
        }
        return null;
    }
    
    private int validarInt(String num){
        try{
            stock=Integer.parseInt(num);
            if(stock<=0){
                JOptionPane.showMessageDialog(null, " ERROR LA CANTIDAD INGRSADA NO ES VALIDA ");
                fieldCantidad.setText("");
                return 0;
            }
            fieldCantidad.setEnabled(false);
            return stock;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " ERROR LA CANTIDAD INGRSADA NO ES VALIDA ");
            fieldCantidad.setText("");
            return 0;
        }
    }
    
    private String validarStr(String nombreProducto){
        try{
            boolean encontrado=encontrarProducto(nombreProducto);
            if(encontrado || nombreProducto.isEmpty()){
                if(encontrado){
                    JOptionPane.showMessageDialog(null, " EL PRODUCTO YA EXISTE, EL NOMBRE NO ES VALIDO: ");
                }else{
                    JOptionPane.showMessageDialog(null, " ERROR EL NOMBRE INGRESADO NO ES VALIDO: ");
                }
                fieldNombre.setText("");
                return "";
            }
            fieldNombre.setEnabled(false);
            listaAlmacenes.setEnabled(false);
            return nombreProducto;
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " ERROR EL NOMBRE INGRESADO NO ES VALIDO: ");
            fieldNombre.setText("");
            return "";
        }
    }
    
    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        String nombreProducto=fieldNombre.getText();
        nombre=validarStr(nombreProducto);
        if(stock>0 && !nombre.isEmpty()){
            botonGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void fieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCantidadActionPerformed
        String num =fieldCantidad.getText();
        stock = validarInt(num);
        if(stock>0 && !nombre.isEmpty()){
            botonGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_fieldCantidadActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        Product producto=new Product(nombre, stock);
        for (Warehouse almacen : almacenes) {
            if(almacenSeleccionadoW.name.equals(almacen.name)){
                almacen.products.pushBack(producto);
                fieldCantidad.setText("");
                fieldCantidad.setEnabled(true);
                listaAlmacenes.setEnabled(true);
                fieldNombre.setText("");
                fieldNombre.setEnabled(true);
                botonGuardar.setEnabled(false);
                break;
            }
        }
    }//GEN-LAST:event_botonGuardarActionPerformed
    
    private void listaAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAlmacenesActionPerformed
        String almacenSeleccionado=listaAlmacenes.getSelectedItem().toString();
        almacenSeleccionadoW=buscarWearhouse(almacenes, almacenSeleccionado);
    }//GEN-LAST:event_listaAlmacenesActionPerformed

    private void fieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNombreFocusLost
        String nombreProducto=fieldNombre.getText();
        nombre=validarStr(nombreProducto);
        if(stock>0 && !nombre.isEmpty()){
            botonGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_fieldNombreFocusLost

    private void fieldCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCantidadFocusLost
        String num =fieldCantidad.getText();
        stock = validarInt(num);
        if(stock>0 && !nombre.isEmpty()){
            botonGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_fieldCantidadFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.backToMainMenu();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField fieldCantidad;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JButton jButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> listaAlmacenes;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    // End of variables declaration//GEN-END:variables
}
