// /*
//  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//  * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
//  */
// package com.proyecto1.gui;

// /**
//  *
//  * @author andresbucarello
//  */
// public class GestionAlmacen extends javax.swing.JFrame {

//     /**
//      * Creates new form GestionAlmacenes
//      */
//     public GestionAlmacen() {
//         initComponents();
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         jLabel2 = new javax.swing.JLabel();
//         jPanel1 = new javax.swing.JPanel();
//         jLabel1 = new javax.swing.JLabel();
//         jScrollPane1 = new javax.swing.JScrollPane();
//         jTable1 = new javax.swing.JTable();
//         jButton1 = new javax.swing.JButton();
//         jButton2 = new javax.swing.JButton();
//         jButton3 = new javax.swing.JButton();
//         jButton4 = new javax.swing.JButton();
//         jButton5 = new javax.swing.JButton();

//         jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("./assets/logoAmazon.png"))); // NOI18N

//         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//         getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

//         jPanel1.setMinimumSize(new java.awt.Dimension(632, 450));
//         jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

//         jLabel1.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
//         jLabel1.setText("ALMACENES");
//         jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

//         jTable1.setFont(new java.awt.Font("Silom", 0, 10)); // NOI18N
//         jTable1.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null},
//                 {null, null, null, null},
//                 {null, null, null, null},
//                 {null, null, null, null}
//             },
//             new String [] {
//                 "Title 1", "Title 2", "Title 3", "Title 4"
//             }
//         ));
//         jScrollPane1.setViewportView(jTable1);

//         jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 570, 290));

//         jButton1.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
//         jButton1.setText("Agregar Almacen");
//         jButton1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jButton1ActionPerformed(evt);
//             }
//         });
//         jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

//         jButton2.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
//         jButton2.setText("Agregar Producto");
//         jButton2.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jButton2ActionPerformed(evt);
//             }
//         });
//         jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

//         jButton3.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
//         jButton3.setText("Guardar");
//         jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

//         jButton4.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
//         jButton4.setText("Retroceder");
//         jButton4.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jButton4ActionPerformed(evt);
//             }
//         });
//         jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

//         jButton5.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
//         jButton5.setText("Agregar Ruta");
//         jButton5.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jButton5ActionPerformed(evt);
//             }
//         });
//         jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

//         getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

//         pack();
//     }// </editor-fold>//GEN-END:initComponents

//     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jButton1ActionPerformed

//     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jButton2ActionPerformed

//     private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jButton4ActionPerformed

//     private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jButton5ActionPerformed

//     /**
//      * @param args the command line arguments
//      */
//     public static void main(String args[]) {
//         /* Set the Nimbus look and feel */
//         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//         /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//          * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//          */
//         try {
//             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                 if ("Nimbus".equals(info.getName())) {
//                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                     break;
//                 }
//             }
//         } catch (ClassNotFoundException ex) {
//             java.util.logging.Logger.getLogger(GestionAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (InstantiationException ex) {
//             java.util.logging.Logger.getLogger(GestionAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (IllegalAccessException ex) {
//             java.util.logging.Logger.getLogger(GestionAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//             java.util.logging.Logger.getLogger(GestionAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         }
//         //</editor-fold>
//         //</editor-fold>

//         /* Create and display the form */
//         java.awt.EventQueue.invokeLater(new Runnable() {
//             public void run() {
//                 new GestionAlmacen().setVisible(true);
//             }
//         });
//     }

//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private javax.swing.JButton jButton1;
//     private javax.swing.JButton jButton2;
//     private javax.swing.JButton jButton3;
//     private javax.swing.JButton jButton4;
//     private javax.swing.JButton jButton5;
//     private javax.swing.JLabel jLabel1;
//     private javax.swing.JLabel jLabel2;
//     private javax.swing.JPanel jPanel1;
//     private javax.swing.JScrollPane jScrollPane1;
//     private javax.swing.JTable jTable1;
//     // End of variables declaration//GEN-END:variables
// }
