package com.proyecto1.gui;

import com.proyecto1.containers.Graph;
import com.proyecto1.containers.Vector;
import com.proyecto1.models.Product;
import com.proyecto1.models.Warehouse;
import java.awt.Color;
import java.awt.event.ActionEvent;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

// @author andresbucarello

public class ModificarStock extends MenuComponent {
    
    Vector<Warehouse> almacenes;
    Vector<Product> products;
    Warehouse almacenSeleccionadoW;
    Product productoSeleccionadoP;
    int stock;
    DefaultComboBoxModel<String> productosDisponibles = new DefaultComboBoxModel();
    
    /**
     * Creates new form ModificarStockk
     */
    //Funcion para modficar el stock mediante al input del usuario
    public ModificarStock(MainPanel mainMenuPanel) {
        //Se usa herencia de la clase padre inicial que es el main menu
        super(mainMenuPanel);
        initComponents();
        //Se importa el metodo de los grafos
        almacenes= Graph.getInstance().warehouses;
        //Se crea una combobox para los warehouse
        DefaultComboBoxModel<String> waerhouseComboBoxModel = new DefaultComboBoxModel<>();
        for (Warehouse w : almacenes)
            waerhouseComboBoxModel.addElement(w.name);
        this.listaAlmacenes.setModel(waerhouseComboBoxModel);
        //Se le resta uno para que sea exactamente el input del usuario (si no este comenzaria en 0)
        this.listaAlmacenes.setSelectedIndex(-1);

        this.listaProductos.setModel(this.productosDisponibles);
        this.reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        listaAlmacenes = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        titulo3 = new javax.swing.JLabel();
        listaProductos = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        titulo4 = new javax.swing.JLabel();
        fieldCantidad = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        retrocederPanel = new javax.swing.JPanel();
        retrocederText = new javax.swing.JLabel();
        modificarBtn = new javax.swing.JButton();

        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(960, 720));
        setMinimumSize(new java.awt.Dimension(960, 720));
        setPreferredSize(new java.awt.Dimension(960, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo1.setFont(new java.awt.Font("SansSerif", 1, 70)); // NOI18N
        titulo1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("MODIFICAR STOCK");
        titulo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 960, 100));

        titulo2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        titulo2.setForeground(new java.awt.Color(242, 242, 242));
        titulo2.setText("SELECCIONE EL ALMACEN :");
        titulo2.setToolTipText("");
        add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 360, 40));

        listaAlmacenes.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        listaAlmacenes.setForeground(new java.awt.Color(51, 109, 174));
        listaAlmacenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaAlmacenes.setToolTipText("");
        listaAlmacenes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Almacenes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("SansSerif", 0, 13))); // NOI18N
        listaAlmacenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listaAlmacenes.setName(""); // NOI18N
        listaAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAlmacenesActionPerformed(evt);
            }
        });
        add(listaAlmacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 520, 70));

        jSeparator1.setForeground(new java.awt.Color(51, 109, 174));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 860, 20));

        titulo3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        titulo3.setForeground(new java.awt.Color(242, 242, 242));
        titulo3.setText("SELECCIONE EL NOMBRE DEL PRODUCTO :");
        titulo3.setToolTipText("");
        add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 530, 40));

        listaProductos.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        listaProductos.setForeground(new java.awt.Color(51, 109, 174));
        listaProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaProductos.setToolTipText("");
        listaProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 13))); // NOI18N
        listaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaProductosActionPerformed(evt);
            }
        });
        add(listaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 330, 60));

        jSeparator2.setForeground(new java.awt.Color(51, 109, 174));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 860, 20));

        titulo4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        titulo4.setForeground(new java.awt.Color(242, 242, 242));
        titulo4.setText("INGRESE LA CANTIDAD A AUMENTAR  DEL PRODUCTO :");
        titulo4.setToolTipText("");
        add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 690, 30));

        fieldCantidad.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        fieldCantidad.setForeground(new java.awt.Color(51, 109, 174));
        fieldCantidad.setToolTipText("");
        fieldCantidad.setBorder(null);
        fieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCantidadActionPerformed(evt);
            }
        });
        add(fieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 160, 40));
        fieldCantidad.getAccessibleContext().setAccessibleName("");

        jSeparator3.setForeground(new java.awt.Color(51, 109, 174));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 860, 20));

        retrocederPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        retrocederText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        retrocederText.setForeground(new java.awt.Color(255, 255, 255));
        retrocederText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        retrocederText.setText("<");
        retrocederText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retrocederTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                retrocederTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retrocederTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout retrocederPanelLayout = new javax.swing.GroupLayout(retrocederPanel);
        retrocederPanel.setLayout(retrocederPanelLayout);
        retrocederPanelLayout.setHorizontalGroup(
            retrocederPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(retrocederText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        retrocederPanelLayout.setVerticalGroup(
            retrocederPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(retrocederText, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(retrocederPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        modificarBtn.setText("Modificar");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAction(evt);
            }
        });
        add(modificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 630, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void reset() {
        this.listaProductos.setEnabled(false);
        this.fieldCantidad.setEnabled(false);
        this.modificarBtn.setEnabled(false);
        this.fieldCantidad.setText("");
    }
    //Se reinicia la ventana 
    //Esta opcion es para que en caso que el usuario no escoja un almacen se active un JOptionPane con el mensaje de error
    protected void modificarAction(ActionEvent evt) {
        if (this.almacenSeleccionadoW == null)
            JOptionPane.showMessageDialog(this,
                String.format("Ningun almacen fue seleccionado, seleccione uno por favor"), "ERROR",
                JOptionPane.ERROR_MESSAGE);
        
        //Se ontiene la cantidad verdadera del producto elegido por el usuario
        String num = fieldCantidad.getText();
        stock = validarInt(num);
        if (stock == 0) return;
        this.productoSeleccionadoP.stock += stock;
        Graph.getInstance().needsSave = true;
        this.reset();   
    }
    //Se valida en el caso de que el usuario no ponga un numero entero
    private int validarInt(String num){
        try{
            stock=Integer.parseInt(num);
            if(stock<=0){
                JOptionPane.showMessageDialog(null, " ERROR LA CANTIDAD INGRESADA NO ES VALIDA ");
                fieldCantidad.setText("");
                return 0;
            }
            fieldCantidad.setEnabled(false);
            return stock;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " ERROR LA CANTIDAD INGRESADA NO ES VALIDA ");
            fieldCantidad.setText("");
            return 0;
        }
    }
    
    private void fieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCantidadActionPerformed
    }//GEN-LAST:event_fieldCantidadActionPerformed
    //Funcion para que se seleccionen y se muestren las listas correctamente
    private void listaAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAlmacenesActionPerformed
        int wIndex = this.listaAlmacenes.getSelectedIndex();
        if (wIndex < 0) return;
        this.almacenSeleccionadoW = this.almacenes.get(wIndex);
        this.products = this.almacenSeleccionadoW.products;

        this.productosDisponibles = new DefaultComboBoxModel<>();
        for (Product p : this.products)
            this.productosDisponibles.addElement(p.name);
        this.listaProductos.setModel(this.productosDisponibles);
        
        this.listaProductos.setEnabled(true);
        this.fieldCantidad.setEnabled(true);
        this.modificarBtn.setEnabled(true);

        this.productoSeleccionadoP = this.products.get(0);
    }//GEN-LAST:event_listaAlmacenesActionPerformed

    private void listaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaProductosActionPerformed
        int pIndex = this.listaProductos.getSelectedIndex();
        this.productoSeleccionadoP = this.products.get(pIndex);
    }//GEN-LAST:event_listaProductosActionPerformed

    private void retrocederTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrocederTextMouseClicked
        this.backToMainMenu();
    }//GEN-LAST:event_retrocederTextMouseClicked

    private void retrocederTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrocederTextMouseEntered
        retrocederPanel.setBackground(Color.red);
    }//GEN-LAST:event_retrocederTextMouseEntered

    private void retrocederTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrocederTextMouseExited
        retrocederPanel.setBackground(Color.darkGray);
    }//GEN-LAST:event_retrocederTextMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldCantidad;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> listaAlmacenes;
    private javax.swing.JComboBox<String> listaProductos;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JPanel retrocederPanel;
    private javax.swing.JLabel retrocederText;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    // End of variables declaration//GEN-END:variables
}
