package proyecto1.estruturasdedatos.gui;

import proyecto1.estruturasdedatos.containers.Graph;
import proyecto1.estruturasdedatos.containers.Vector;
import proyecto1.estruturasdedatos.models.Product;
import proyecto1.estruturasdedatos.models.Warehouse;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

// @author andresbucarello

public class ModificarStock extends javax.swing.JPanel {
    
    Vector<Warehouse> almacenes;
    Warehouse almacenSeleccionadoW;
    Product productoSeleccionadoP;
    int stock;
    DefaultComboBoxModel<String> almacenesDisponibles = new DefaultComboBoxModel();
    DefaultComboBoxModel<String> productosDisponibles = new DefaultComboBoxModel();
    
    /**
     * Creates new form ModificarStockk
     */
    public ModificarStock() {
        initComponents();
        
        almacenes= Graph.getInstance().warehouses;
        cargarComboAlmacenes(listaAlmacenes);
        listaProductos.setModel(productosDisponibles);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        listaAlmacenes = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        titulo3 = new javax.swing.JLabel();
        listaProductos = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        titulo4 = new javax.swing.JLabel();
        fieldCantidad = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        botonModificar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(960, 720));
        setMinimumSize(new java.awt.Dimension(960, 720));
        setPreferredSize(new java.awt.Dimension(960, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo1.setFont(new java.awt.Font("Silom", 0, 65)); // NOI18N
        titulo1.setText("MODIFICAR STOCK");
        add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        titulo2.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        titulo2.setText("SELECCIONE EL ALMACEN :");
        add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 330, -1));

        listaAlmacenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAlmacenesActionPerformed(evt);
            }
        });
        add(listaAlmacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 520, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 850, 20));

        titulo3.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        titulo3.setText("SELECCIONE EL NOMBRE DEL PRODUCTO :");
        add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 490, 20));

        listaProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaProductosActionPerformed(evt);
            }
        });
        add(listaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 313, 350, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 850, 20));

        titulo4.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        titulo4.setText("INGRESE LA CANTIDAD A AUMENTAR  DEL PRODUCTO :");
        add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 640, 20));

        fieldCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCantidadFocusLost(evt);
            }
        });
        fieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCantidadActionPerformed(evt);
            }
        });
        add(fieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 220, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 850, 20));

        botonModificar.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
        botonModificar.setText("MODIFICAR");
        botonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificar.setEnabled(false);
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });
        add(botonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 250, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1/estruturasdedatos/assets/left-arrow.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    private void cargarComboAlmacenes(JComboBox c) {
        c.setModel(almacenesDisponibles);
        for (Warehouse almacen: almacenes) {
            almacenesDisponibles.addElement(almacen.name);
        }
    }
    
    private Warehouse buscarWearhouse(Vector<Warehouse> almacenes, String nombre){
        for (Warehouse almacen : almacenes) {
            if(nombre.equals(almacen.name)){
                return almacen;    
            }
        }
        return null;
    }
    
    private Product buscarProducto(String nombreAlmacen,String nombreProducto){
        for (Warehouse almacen : almacenes) {
            if(nombreAlmacen.equals(almacen.name)){
                for(Product producto: almacen.products){
                    if(producto.name.equalsIgnoreCase(nombreProducto)){
                        return producto;   
                    }
                } 
            }
        }
        return null;
    }
    
    private int validarInt(String num){
        try{
            stock=Integer.parseInt(num);
            if(stock<=0){
                JOptionPane.showMessageDialog(null, " ERROR LA CANTIDAD INGRSADA NO ES VALIDA ");
                fieldCantidad.setText("");
                return 0;
            }
            fieldCantidad.setEnabled(false);
            return stock;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " ERROR LA CANTIDAD INGRSADA NO ES VALIDA ");
            fieldCantidad.setText("");
            return 0;
        }
    }
    
    private void fieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCantidadActionPerformed
        String num =fieldCantidad.getText();
        stock = validarInt(num);
        if(stock>0){
            botonModificar.setEnabled(true);
        }
    }//GEN-LAST:event_fieldCantidadActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed

        for (Warehouse almacen : almacenes){
            if(almacenSeleccionadoW.name.equals(almacen.name)){
                for (Product producto : almacen.products){
                    if(productoSeleccionadoP.name.equals(producto.name)){
                        producto.stock+=stock;
                    }
                }
            }    
        }
        botonModificar.setEnabled(false);
        fieldCantidad.setText("");
        fieldCantidad.setEnabled(true);
    }//GEN-LAST:event_botonModificarActionPerformed

    private void listaAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAlmacenesActionPerformed
        String almacenSeleccionado=listaAlmacenes.getSelectedItem().toString();
        almacenSeleccionadoW=buscarWearhouse(almacenes, almacenSeleccionado);
        productosDisponibles.removeAllElements();
        for (Warehouse almacen: almacenes) {
            if(almacenSeleccionadoW.name.equalsIgnoreCase(almacen.name)){
                for (Product producto : almacen.products) {
                    productosDisponibles.addElement(producto.name);
                }
            }
        }
    }//GEN-LAST:event_listaAlmacenesActionPerformed

    private void listaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaProductosActionPerformed
        try{
            String productoSeleccionado=listaProductos.getSelectedItem().toString();
            productoSeleccionadoP=buscarProducto(almacenSeleccionadoW.name,productoSeleccionado);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_listaProductosActionPerformed

    private void fieldCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCantidadFocusLost
        String num =fieldCantidad.getText();
        stock = validarInt(num);
        if(stock>0){
            botonModificar.setEnabled(true);
        }
    }//GEN-LAST:event_fieldCantidadFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModificar;
    private javax.swing.JTextField fieldCantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> listaAlmacenes;
    private javax.swing.JComboBox<String> listaProductos;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    // End of variables declaration//GEN-END:variables
}
