/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto1.gui;

/**
 *
 * @author andresbucarello
 */
public class AgregarProducto extends javax.swing.JFrame {

    /**
     * Creates new form AgregarProducto
     */
    public AgregarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonRetroceder = new javax.swing.JButton();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        listaAlmacenes = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        titulo3 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        botonComprobar1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        titulo4 = new javax.swing.JLabel();
        fieldPrecio = new javax.swing.JTextField();
        botonComprobar2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        titulo5 = new javax.swing.JLabel();
        fieldCantidad = new javax.swing.JTextField();
        botonComprobar3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        botonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRetroceder.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retroceder.png"))); // NOI18N
        botonRetroceder.setBorder(null);
        botonRetroceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetrocederActionPerformed(evt);
            }
        });
        jPanel1.add(botonRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        titulo1.setFont(new java.awt.Font("Silom", 0, 48)); // NOI18N
        titulo1.setText("AGREGAR PRODUCTO");
        jPanel1.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        titulo2.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo2.setText("SELECCIONE EL ALMACEN :");
        jPanel1.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, -1));

        listaAlmacenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(listaAlmacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 150, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 580, 20));

        titulo3.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo3.setText("INGRESE EL NOMBRE DEL PRODUCTO :");
        jPanel1.add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 20));

        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(fieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 190, 20));

        botonComprobar1.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonComprobar1.setText("COMPROBAR");
        botonComprobar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonComprobar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprobar1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonComprobar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 120, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 580, 20));

        titulo4.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo4.setText("INGRESE EL PRECIO DEL PRODUCTO :");
        jPanel1.add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 20));

        fieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(fieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 190, 20));

        botonComprobar2.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonComprobar2.setText("COMPROBAR");
        botonComprobar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonComprobar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprobar2ActionPerformed(evt);
            }
        });
        jPanel1.add(botonComprobar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 120, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 580, 20));

        titulo5.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo5.setText("INGRESE LA CANTIDAD DEL PRODUCTO :");
        jPanel1.add(titulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 280, 20));

        fieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(fieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 170, 20));

        botonComprobar3.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonComprobar3.setText("COMPROBAR");
        botonComprobar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonComprobar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprobar3ActionPerformed(evt);
            }
        });
        jPanel1.add(botonComprobar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 120, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 580, 20));

        botonGuardar.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRetrocederActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRetrocederActionPerformed

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void botonComprobar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprobar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonComprobar1ActionPerformed

    private void fieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPrecioActionPerformed

    private void botonComprobar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprobar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonComprobar2ActionPerformed

    private void fieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCantidadActionPerformed

    private void botonComprobar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprobar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonComprobar3ActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComprobar1;
    private javax.swing.JButton botonComprobar2;
    private javax.swing.JButton botonComprobar3;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonRetroceder;
    private javax.swing.JTextField fieldCantidad;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldPrecio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox<String> listaAlmacenes;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    private javax.swing.JLabel titulo5;
    // End of variables declaration//GEN-END:variables
}
